# Generated by Django 5.2.17 on 2026-08-16 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, verbose_name='发送的验证码')),
                ('email_type', models.CharField(choices=[('register', '注册'), ('forget', '找回密码'), ('change_pwd', '修改密码'), ('change_email_new', '修改邮箱'), ('complete', '补全信息'), ('delete', '注销账号')], default='register', max_length=20, verbose_name='邮件类型')),
                ('is_active', models.BooleanField(default=True)),
                ('create_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': '邮箱验证码',
                'verbose_name_plural': '邮箱验证码',
            },
        ),
    ]
