# Generated by Django 5.2.17 on 2026-08-16 14:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='email',
            name='email',
            field=models.CharField(default=datetime.datetime(2026, 8, 16, 14, 59, 1, 462551, tzinfo=datetime.timezone.utc), max_length=64, verbose_name='邮件地址'),
            preserve_default=False,
        ),
    ]
