# Generated by Django 5.2.17 on 2026-08-15 14:33

from django.db import migrations, models

import catalog.models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="JDProduct",
            fields=[
                (
                    "jd_uuid",
                    models.UUIDField(
                        default=catalog.models.generate_uuid7,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="商品UUID",
                    ),
                ),
                (
                    "categoryInfo",
                    models.JSONField(blank=True, default=dict, verbose_name="类目信息"),
                ),
                ("comments", models.IntegerField(verbose_name="评论数")),
                (
                    "commissionInfo",
                    models.JSONField(blank=True, default=dict, verbose_name="佣金信息"),
                ),
                (
                    "couponInfo",
                    models.JSONField(blank=True, default=dict, verbose_name="优惠券信息"),
                ),
                ("goodCommentsShare", models.FloatField(verbose_name="商品好评率")),
                ("imageInfo", models.JSONField(blank=True, default=dict, verbose_name="图片信息")),
                ("inOrderCount30Days", models.IntegerField(verbose_name="30天引单数量")),
                ("materialUrl", models.CharField(max_length=256, verbose_name="联盟商品链接")),
                ("priceInfo", models.JSONField(blank=True, default=dict, verbose_name="价格信息")),
                ("shopInfo", models.JSONField(blank=True, default=dict, verbose_name="店铺信息")),
                ("skuId", models.BigIntegerField(unique=True, verbose_name="商品id")),
                ("skuName", models.CharField(max_length=256, verbose_name="商品名称")),
                ("isHot", models.BooleanField(default=False, verbose_name="是否爆款")),
                (
                    "spuid",
                    models.BigIntegerField(blank=True, null=True, verbose_name="同款商品主SKU ID"),
                ),
                ("brandCode", models.CharField(blank=True, max_length=64, verbose_name="品牌编码")),
                (
                    "brandName",
                    models.CharField(blank=True, max_length=128, verbose_name="品牌名称"),
                ),
                ("owner", models.CharField(blank=True, max_length=1, verbose_name="商品类型")),
                ("pinGouInfo", models.JSONField(blank=True, default=dict, verbose_name="拼购信息")),
                (
                    "resourceInfo",
                    models.JSONField(blank=True, default=dict, verbose_name="资源信息"),
                ),
                (
                    "inOrderCount30DaysSku",
                    models.IntegerField(default=0, verbose_name="30天SKU引单数量"),
                ),
                (
                    "seckillInfo",
                    models.JSONField(blank=True, default=dict, verbose_name="秒杀信息"),
                ),
                (
                    "jxFlags",
                    models.JSONField(blank=True, default=list, verbose_name="京喜商品类型"),
                ),
                ("videoInfo", models.JSONField(blank=True, default=dict, verbose_name="视频信息")),
                (
                    "documentInfo",
                    models.JSONField(blank=True, default=dict, verbose_name="文案信息"),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="创建时间")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="更新时间")),
            ],
            options={
                "verbose_name": "京东商品",
                "verbose_name_plural": "京东商品",
                "db_table": "catalog_jd_product",
                "ordering": ("-created_at",),
            },
        ),
    ]
