# Generated by Django 5.2.17 on 2026-08-15 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("catalog", "0002_jdproduct"),
    ]

    operations = [
        migrations.AddField(
            model_name="jdproduct",
            name="activityCardInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="超市购物卡明细"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="bonusInfoList",
            field=models.JSONField(blank=True, default=list, verbose_name="联盟奖励活动集合"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="bookInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="图书信息"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="companyType",
            field=models.IntegerField(blank=True, null=True, verbose_name="商家类型"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="deliveryType",
            field=models.BooleanField(default=False, verbose_name="是否京东配送"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="forbidTypes",
            field=models.JSONField(blank=True, default=list, verbose_name="禁售类型"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="isOversea",
            field=models.BooleanField(default=False, verbose_name="是否全球购商品"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="itemId",
            field=models.CharField(
                blank=True, db_index=True, max_length=128, verbose_name="联盟商品ID"
            ),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="kaAdowner",
            field=models.BooleanField(default=False, verbose_name="是否星选商家商品"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="preSaleInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="预售信息"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="promotionLabelInfoList",
            field=models.JSONField(blank=True, default=list, verbose_name="商品促销标签集"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="purchasePriceInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="到手价明细"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="reserveInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="预约信息"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="secondPriceInfoList",
            field=models.JSONField(blank=True, default=list, verbose_name="双价格信息"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="skuLabelInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="商品标签"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="skuTagList",
            field=models.JSONField(blank=True, default=list, verbose_name="联盟标签"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="smartDocumentInfoList",
            field=models.JSONField(blank=True, default=list, verbose_name="智能推广文案集合"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="solitaireActivity",
            field=models.JSONField(blank=True, default=dict, verbose_name="订单接龙活动信息"),
        ),
        migrations.AddField(
            model_name="jdproduct",
            name="specialSkuUrlInfo",
            field=models.JSONField(blank=True, default=dict, verbose_name="频道页信息"),
        ),
    ]
