# Generated by Django 5.2.17 on 2026-08-15 14:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_jdproduct_activitycardinfo_jdproduct_bonusinfolist_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdproduct',
            name='jd_uuid',
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
