# Generated by Django 5.2.17 on 2026-08-17 07:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_remove_jdproduct_jd_uuid_jdproduct_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_id', models.IntegerField(max_length=10, verbose_name='类目id')),
                ('name', models.CharField(max_length=48, verbose_name='类目名称')),
                ('grade', models.SmallIntegerField(max_length=1, verbose_name='类目级别(类目级别 0，1，2 代表一、二、三级类目)')),
                ('parentId', models.IntegerField(max_length=10, verbose_name='主类目id')),
            ],
        ),
    ]
