# Generated by Django 5.2.17 on 2026-08-17 07:34

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_channel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='jdproduct',
            name='categoryInfo',
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='cid1',
            field=models.IntegerField(default=1, verbose_name='一级类目id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='cid1Name',
            field=models.CharField(default=django.utils.timezone.now, max_length=100, verbose_name='一级类目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='cid2',
            field=models.IntegerField(default=1, verbose_name='二级类目id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='cid2Name',
            field=models.CharField(default=1, max_length=100, verbose_name='二级类目'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='cid3',
            field=models.IntegerField(default=1, verbose_name='三级类目id'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='jdproduct',
            name='cid3Name',
            field=models.CharField(default=1, max_length=100, verbose_name='三级类目'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='channel',
            name='channel_id',
            field=models.IntegerField(verbose_name='类目id'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='grade',
            field=models.SmallIntegerField(verbose_name='类目级别(类目级别 0，1，2 代表一、二、三级类目)'),
        ),
        migrations.AlterField(
            model_name='channel',
            name='parentId',
            field=models.IntegerField(verbose_name='主类目id'),
        ),
    ]
