# Generated by Django 5.2.17 on 2026-08-17 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_remove_jdproduct_categoryinfo_jdproduct_cid1_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jdproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='商品价格'),
            preserve_default=False,
        ),
    ]
